### ISSUE TITLE
NameError: uninitialized constant Zip::Error

### ISSUE THREAD

**Issue by LegendSzymon-P** [weshatheleopard/rubyXL#147]
When I'm trying to parse any xls file by:

```
RubyXL::Parser.parse('sheet.xls')
```

I'm getting the following error:

```
NameError: uninitialized constant Zip::Error
    from /home/szymon/.rvm/gems/ruby-2.0.0-p481/gems/rubyXL-3.1.0/lib/rubyXL/objects/root.rb:83:in `rescue in parse_file'
    from /home/szymon/.rvm/gems/ruby-2.0.0-p481/gems/rubyXL-3.1.0/lib/rubyXL/objects/root.rb:74:in `parse_file'
    from /home/szymon/.rvm/gems/ruby-2.0.0-p481/gems/rubyXL-3.1.0/lib/rubyXL/parser.rb:19:in `parse'
    from /home/szymon/.rvm/gems/ruby-2.0.0-p481/gems/rubyXL-3.1.0/lib/rubyXL/parser.rb:9:in `parse'
    from (irb):1
    from /home/szymon/.rvm/gems/ruby-2.0.0-p481/gems/railties-3.2.17/lib/rails/commands/console.rb:47:in `start'
    from /home/szymon/.rvm/gems/ruby-2.0.0-p481/gems/railties-3.2.17/lib/rails/commands/console.rb:8:in `start'
    from /home/szymon/.rvm/gems/ruby-2.0.0-p481/gems/railties-3.2.17/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

I'm using Rails 3.2.17, Ruby 2.0.0. I have rubyzip 1.0.0 and rubyXL 3.1.0

**Comment by khiav223577** [comment]
Upgrade rubyXL from `3.1.0` to `3.4.25` fix my problem
