### ISSUE TITLE
Can't add new worksheets

### ISSUE THREAD

**Issue by ludste** [weshatheleopard/rubyXL#200]
#### Setup
* Windows 7 64-bit
* Ruby 2.1.6p336
* RubyXL 3.3.12
* Nokogori 1.6.6.2

#### Problem. 
I create an empty workbook using Excel and save it as test.xlxs. (I have also tried to create a new workbook using rubyXL). When I want to add a new worksheet, I get an error when I try to save the file. 

```
#<ArgumentError: comparison of NilClass with 1 failed>["C:/Ruby21-
x64/lib/ruby/gems/2.1.0/gems/rubyXL-3.3.12/lib/rubyXL/objects/workbook.rb:359:in `each'", 
"C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rubyXL-3.3.12/lib/rubyXL/objects/workbook.rb:359:in 
`max_by'", "C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rubyXL-
3.3.12/lib/rubyXL/objects/workbook.rb:359:in `before_write_xml'", "C:/Ruby21-
x64/lib/ruby/gems/2.1.0/gems/rubyXL-3.3.12/lib/rubyXL/objects/ooxml_object.rb:275:in `write_xml'", 
"C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rubyXL-3.3.12/lib/rubyXL/objects/ooxml_object.rb:269:in 
`write_xml'", "C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rubyXL-
3.3.12/lib/rubyXL/objects/ooxml_object.rb:438:in `add_to_zip'", "C:/Ruby21-
x64/lib/ruby/gems/2.1.0/gems/rubyXL-3.3.12/lib/rubyXL/objects/root.rb:51:in `block (3 levels) in 
stream'", "C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rubyXL-3.3.12/lib/rubyXL/objects/root.rb:49:in 
`each'", "C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rubyXL-3.3.12/lib/rubyXL/objects/root.rb:49:in `block 
(2 levels) in stream'", "C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rubyXL-
3.3.12/lib/rubyXL/objects/root.rb:47:in `each'", "C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rubyXL-
3.3.12/lib/rubyXL/objects/root.rb:47:in `block in stream'", "C:/Ruby21-
x64/lib/ruby/gems/2.1.0/gems/rubyzip-1.1.7/lib/zip/output_stream.rb:61:in `write_buffer'", "C:/Ruby21-
x64/lib/ruby/gems/2.1.0/gems/rubyXL-3.3.12/lib/rubyXL/objects/root.rb:37:in `stream'", "C:/Ruby21-
x64/lib/ruby/gems/2.1.0/gems/rubyXL-3.3.12/lib/rubyXL/objects/workbook.rb:393:in `block in save'", 
"C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rubyXL-3.3.12/lib/rubyXL/objects/workbook.rb:393:in `open'", 
"C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rubyXL-3.3.12/lib/rubyXL/objects/workbook.rb:393:in `save'", 
"rubyXL.rb:13:in `<main>'"]
zlib(finalizer): the stream was freed prematurely
```

This is the code I'm running:

```ruby
require 'rubyXL'
#workbook = RubyXL::Workbook.new
workbook = RubyXL::Parser.parse("./test.xlsx")
sheet = workbook.add_worksheet('Test')
workbook.write("./test.xlsx")
```

**Comment by weshatheleopard** [comment]
require 'rubyXL'
workbook = RubyXL::Workbook.new
workbook.write("test.xlsx")

workbook = RubyXL::Parser.parse("test.xlsx")
sheet = workbook.add_worksheet('Test')
workbook.write("./test2.xlsx")
