### ISSUE TITLE
Storage class not found for docProps/app.xml and xl/workbook.xml leading to error opening file

### ISSUE THREAD

**Issue by rcuhljr** [weshatheleopard/rubyXL#443]
I receive two warnings during attempts to parse the file, and then the process fails with

```
*** WARNING: storage class not found for docProps/app.xml (http://purl.oclc.org/ooxml/officeDocument/relationships/extendedProperties)
*** WARNING: storage class not found for xl/workbook.xml (http://purl.oclc.org/ooxml/officeDocument/relationships/officeDocument)
WARNING: RubyXL::WorkbookRoot is not aware how to process RubyXL::GenericStorageObject
WARNING: RubyXL::WorkbookRoot is not aware how to process RubyXL::GenericStorageObject
NoMethodError: undefined method `root=' for nil:NilClass
from [snip].asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rubyXL-3.4.22/lib/rubyXL/objects/root.rb:69:in `parse_zip_file'
```

The file was an .xls file from the CMS.gov website, https://www.cms.gov/medicare/medicare-part-b-drug-average-sales-price/2023-asp-drug-pricing-files the `July 2023 ASP Pricing File` which was opened in excel and saved as an xlsx file with no changes.

Here is the copy I tested with to reproduce the issue our users are seeing. [CopyJuly_2023_ASP_Pricing_File_060223.xlsx](https://github.com/weshatheleopard/rubyXL/files/11709580/CopyJuly_2023_ASP_Pricing_File_060223.xlsx)

**Comment by DcsMarionDickten** [comment]
I had the same error, using RubyXL Version 3.4.33. Since my file contains personal data, I unfortunately cannot post it, but it's the exact same error.

**Comment by DcsMarionDickten** [comment]
I switched on debugging mode, but it didn't give me any info I can make sense of. Here is the bit that is output:
```
Exception `NameError' at /Users/marion/.rvm/gems/ruby-3.2.3/gems/rubyXL-3.4.33/lib/rubyXL/objects/ooxml_object.rb:16 - uninitialized class variable @@ooxml_attributes in RubyXL::ContentTypes
Exception `NameError' at /Users/marion/.rvm/gems/ruby-3.2.3/gems/rubyXL-3.4.33/lib/rubyXL/objects/ooxml_object.rb:16 - uninitialized class variable @@ooxml_child_nodes in RubyXL::ContentTypeDefault
Exception `NameError' at /Users/marion/.rvm/gems/ruby-3.2.3/gems/rubyXL-3.4.33/lib/rubyXL/objects/ooxml_object.rb:16 - uninitialized class variable @@ooxml_child_nodes in RubyXL::ContentTypeOverride
Exception `NameError' at /Users/marion/.rvm/gems/ruby-3.2.3/gems/rubyXL-3.4.33/lib/rubyXL/objects/ooxml_object.rb:16 - uninitialized class variable @@ooxml_attributes in RubyXL::OOXMLRelationshipsFile
Exception `NameError' at /Users/marion/.rvm/gems/ruby-3.2.3/gems/rubyXL-3.4.33/lib/rubyXL/objects/ooxml_object.rb:16 - uninitialized class variable @@ooxml_child_nodes in RubyXL::Relationship
*** WARNING: storage class not found for docProps/app.xml (http://purl.oclc.org/ooxml/officeDocument/relationships/extendedProperties)
Exception `NameError' at /Users/marion/.rvm/gems/ruby-3.2.3/gems/rubyXL-3.4.33/lib/rubyXL/objects/ooxml_object.rb:16 - uninitialized class variable @@ooxml_attributes in RubyXL::CorePropertiesFile
Exception `NameError' at /Users/marion/.rvm/gems/ruby-3.2.3/gems/rubyXL-3.4.33/lib/rubyXL/objects/ooxml_object.rb:16 - uninitialized class variable @@ooxml_child_nodes in RubyXL::StringNode
Exception `NameError' at /Users/marion/.rvm/gems/ruby-3.2.3/gems/rubyXL-3.4.33/lib/rubyXL/objects/ooxml_object.rb:16 - uninitialized class variable @@ooxml_child_nodes in RubyXL::StringNodeW3C
*** WARNING: storage class not found for xl/workbook.xml (http://purl.oclc.org/ooxml/officeDocument/relationships/officeDocument)
WARNING: RubyXL::WorkbookRoot is not aware how to process RubyXL::GenericStorageObject
WARNING: RubyXL::WorkbookRoot is not aware how to process RubyXL::GenericStorageObject
Exception `NoMethodError' at /Users/marion/.rvm/gems/ruby-3.2.3/gems/rubyXL-3.4.33/lib/rubyXL/objects/root.rb:68 - undefined method `root=' for nil:NilClass
Exception `NoMethodError' at /Users/marion/.rvm/gems/ruby-3.2.3/gems/actionpack-6.1.7.7/lib/action_controller/metal/rescue.rb:25 - undefined method `root=' for nil:NilClass
Exception `NoMethodError' at /Users/marion/.rvm/gems/ruby-3.2.3/gems/activesupport-6.1.7.7/lib/active_support/notifications/instrumenter.rb:28 - undefined method `root=' for nil:NilClass
Completed 500 Internal Server Error in 233ms (ActiveRecord: 6.0ms | Allocations: 128669)


Exception `NoMethodError' at /Users/marion/.rvm/gems/ruby-3.2.3/gems/actionpack-6.1.7.7/lib/action_dispatch/middleware/callbacks.rb:30 - undefined method `root=' for nil:NilClass

NoMethodError - undefined method `root=' for nil:NilClass:
  app/models/excel_file_processor.rb:23:in `add_url_col' # this is my own code

```

Of course my project runs 3.4.33, but as far as I could see no changes were made to root.rb between then and now. So this would point to the line

```
def self.parse_zip_file(zip_file)
      root = self.new
      root.content_types = RubyXL::ContentTypes.parse_file(zip_file, ContentTypes::XLSX_PATH)
      root.load_relationships(zip_file, OOXMLTopLevelObject::ROOT)

      wb = root.workbook
      wb.root = root # <== this one
```
which means that wb isn't set. That's as far as I get, sorry.

**Comment by DcsMarionDickten** [comment]
I've pulled the source code from your repo and have put the file that is giving me trouble through your testing routine in `test/test_parse_write.rb`, and I got exactly the same error.

```
MacBookPro:rubyXL marion$ ruby test/test_parse_write.rb 
<<<--- Parsing test/input/Problemdatei.xlsx...
*** WARNING: storage class not found for docProps/app.xml (http://purl.oclc.org/ooxml/officeDocument/relationships/extendedProperties)
*** WARNING: storage class not found for xl/workbook.xml (http://purl.oclc.org/ooxml/officeDocument/relationships/officeDocument)
WARNING: RubyXL::WorkbookRoot is not aware how to process RubyXL::GenericStorageObject
WARNING: RubyXL::WorkbookRoot is not aware how to process RubyXL::GenericStorageObject
/Users/marion/.rvm/gems/ruby-3.2.3/gems/rubyXL-3.4.33/lib/rubyXL/objects/root.rb:68:in `parse_zip_file': undefined method `root=' for nil:NilClass (NoMethodError)

      wb.root = root
        ^^^^^^^
	from /Users/marion/.rvm/gems/ruby-3.2.3/gems/rubyXL-3.4.33/lib/rubyXL/parser.rb:7:in `block in parse'
	from /Users/marion/.rvm/gems/ruby-3.2.3/gems/rubyzip-2.4.1/lib/zip/file.rb:133:in `open'
	from /Users/marion/.rvm/gems/ruby-3.2.3/gems/rubyXL-3.4.33/lib/rubyXL/parser.rb:6:in `parse'
	from test/test_parse_write.rb:9:in `block (2 levels) in <main>'
	from /Users/marion/.rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/benchmark.rb:311:in `realtime'
	from test/test_parse_write.rb:9:in `block in <main>'
	from test/test_parse_write.rb:6:in `each'
	from test/test_parse_write.rb:6:in `<main>'
```

Looking at the stack trace I can see the script didn't use the gem's source code but my installed version of rubyXL-3.4.33, which is not what I wanted, but line 68 in the file rubyXL/objects/root.rb in the pulled code is identical with that of the stack trace.

I tried replacing the personal data contained in the file with "x" and saving it again, using LibreOffice. I was hoping I could then send you the file. However, the edited file does not show the error any more.

Can anybody suggest what to do now...? I would really like to help with tracking this down. I don't seem to be using the testing routine right. It's actually my first time of trying to help with a bug in a Gem.

**Comment by weshatheleopard** [comment]
I am able to parse your file with `3.4.37` with no issues.
